version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: "localstack"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,iam,secretsmanager,ec2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/localstack:/tmp/localstack"
    
  postgres:
      image: postgres:10-alpine
      environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
      volumes:
          - "${PWD}/db-data:/var/lib/postgresql/data"

  local-runner:
      image: amazon/mwaa-local:2.0.2
      user: 1000:1000
      restart: always
      depends_on:
          - postgres
      environment:
          - LOAD_EX=n
          - EXECUTOR=Local
          - AIRFLOW_CONN_AWS_DEFAULT=aws://a:a@?host=http://localstack:4566&region_name=us-east-1
          - AWS_DEFAULT_REGION=us-east-1
          - AWS_PROFILE=default
      volumes:
          - "${PWD}/dags:/usr/local/airflow/dags"
          - "${PWD}/plugins:/usr/local/airflow/plugins"
          - "${PWD}/.aws:/usr/local/airflow/.aws"
      ports:
          - "8080:8080"
      command: local-runner
      healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3

  aws-cli:
    image: mesosphere/aws-cli
    container_name: "aws-cli"
    volumes:
      - ./landing:/tmp/landing:ro
    environment:
      - AWS_ACCESS_KEY_ID=dummyaccess
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        echo Waiting for localstack service start...;
        while ! nc -z localstack 4566;
        do
          sleep 1;
        done;     
        echo Connected!;
     
      aws s3api create-bucket --bucket my-landing-bucket --endpoint-url http://localstack:4566      aws s3 cp /tmp/landing s3://my-landing-bucket --recursive --endpoint-url http://localstack:4566"
    depends_on:
      - localstack